# Note: case is important for the driver name, unlike Rails

development:
  driver: PostgreSQL
  database: example
  timeout: 5000
  username: development
  password: development
  host: localhost
  port: 5432

test:
  driver: PostgreSQL
  database: example
  timeout: 5000
  username: development
  password: development
  host: localhost
  port: 5432
