# Encoding: utf-8

ENV['ENV'] = 'test'

guard :minitest do
  watch(%r{^test/(.*)\/?test_(.*)\.rb})
  watch(%r{^lib/(.*/)?([^/]+)\.rb})     { |m| "test/#{m[1]}test_#{m[2]}.rb" }
  watch(%r{^test/test_helper\.rb})      { 'test' }
end

guard :rubocop, all_on_start: false, cli: ['--format', 'clang'] do
  watch(%r{.+\.rb$})
  watch(%r{^Rakefile})
end