# Encoding: utf-8

require 'yaml'
require 'bundler/gem_tasks'
require 'rake'
require 'rake/testtask'

require_relative './lib/entities'
require_relative './lib/tasks/db'

Rake::TestTask.new do |t|
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end

desc 'Run tests'
task :default => :test
